#./waf --run "scratch/dash --adaptationAlgo=festive --simulationId=1 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tobasco --simulationId=1 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tomato2 --simulationId=1 --BandWidth=75"
./waf --run "scratch/dash --adaptationAlgo=tomato2c --simulationId=1 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=festive --simulationId=2 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tobasco --simulationId=2 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tomato2 --simulationId=2 --BandWidth=75"
./waf --run "scratch/dash --adaptationAlgo=tomato2c --simulationId=2 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=festive --simulationId=3 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tobasco --simulationId=3 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tomato2 --simulationId=3 --BandWidth=75"
./waf --run "scratch/dash --adaptationAlgo=tomato2c --simulationId=3 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=festive --simulationId=4 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tobasco --simulationId=4 --BandWidth=75"
#./waf --run "scratch/dash --adaptationAlgo=tomato2 --simulationId=4 --BandWidth=75"
./waf --run "scratch/dash --adaptationAlgo=tomato2c --simulationId=4 --BandWidth=75"
#cp -r /home/hans/ns-allinone-3.27/ns-3.27/mylogs/* /home/hans/mylogs/BW-75-BF-10/